-- SQLite
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (1, 'Crab and chickpea vindaloo', 6860, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (2, 'Fish and cardamom gyoza', 6982, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (3, 'Gochu jang and chickpea salad', 2288, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (4, 'Spinach and pheasant wontons', 3755, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (5, 'Pumpkin and parmesan soup', 4751, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (6, 'Ginger and parsnip stir fry', 1326, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (7, 'Herring and squab salad', 1792, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (8, 'Rosemary and cardamom bread', 3887, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (9, 'Crayfish and pepper ciabatta', 5903, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (10, 'Persimmon and apple gyoza', 5947, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (11, 'Caerphilly and calamari salad', 6107, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (12, 'Venison and lamb kebab', 7156, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (13, 'Cardamom and black pepper vindaloo', 2510, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (14, 'Jalapeno and cardamom wontons', 3759, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (15, 'Tofu and elderflower pie', 2792, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (16, 'Squash and vermicelli penne', 6783, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (17, 'Pumpkin seed and cream bread', 7132, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (18, 'Lemon and cardamom mousse', 542, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (19, 'Turkey and pork ciabatta', 5155, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (20, 'Parsley and squash wontons', 6409, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (21, 'Quorn and chard curry', 6802, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (22, 'Lobster and rocket penne', 1914, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (23, 'Mushroom and pasta casserole', 4837, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (24, 'Rotini and vacherin salad', 4505, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (25, 'Lavender and sage stir fry', 7060, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (26, 'Chicken and fish kebab', 5588, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (27, 'Pepper and buffalo burgers', 3187, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (28, 'Truffle and dill salad', 6374, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (29, 'Daikon and radicchio stir fry', 6061, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (30, 'Pork sausage meat and le roule cheese salad', 6104, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (31, 'Daikon and cheddar fritters', 2447, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (32, 'Quinoa and bacon salad', 2088, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (33, 'Broccoli and avocado fusilli', 3609, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (34, 'Coriander and plantain vindaloo', 1195, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (35, 'Leek and turkey pie', 4292, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (36, 'Lamb and fregola salad', 6791, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (37, 'Spinach and kipper salad', 1743, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (38, 'Barley and ginger soup', 3321, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (39, 'Cheese and chicken bagel', 1206, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (40, 'Grouse and black pepper bagel', 6916, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (41, 'Hake and lemon salad', 3426, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (42, 'Swordfish salad with garlic dressing', 1822, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (43, 'Cheese and chilli pizza', 1878, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (44, 'Chamomile and creole seasoning salad', 3690, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (45, 'Yuzu and shrimp salad', 3977, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (46, 'Chicken and caviar salad', 5850, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (47, 'Urid dal and horseradish salad', 5369, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (48, 'Ham and tahini toastie', 2465, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (49, 'Angelica and broccoli salad', 6109, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (50, 'Nectarine and persimmon parcels', 6129, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (51, 'Guinea fowl and honeyberry salad', 5507, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (52, 'Jalape and prawn salad', 4026, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (53, 'Veal and feta wontons', 795, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (54, 'Quorn and spinach vindaloo', 6104, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (55, 'Avocado and squash pasta', 5739, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (56, 'Cheese and cardamom burgers', 1845, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (57, 'Sole and chilli dumplings', 1917, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (58, 'Cod and fish wontons', 5867, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (59, 'Samphire and poussin salad', 3037, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (60, 'Mussel and pigeon soup', 5012, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (61, 'Salmon and napolitana pasta', 966, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (62, 'Chicken and pesto dumplings', 5889, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (63, 'Mutton and clementine vindaloo', 6160, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (64, 'Coconut and coriander korma', 5775, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (65, 'Mushroom and cod madras', 3974, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (66, 'Asafoetida and goat korma', 3343, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (67, 'Pork and crayfish panini', 1235, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (68, 'Salmon and pigeon dumplings', 2968, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (69, 'Coffee and trout salad', 5576, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (70, 'Chilli and salmon penne', 3462, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (71, 'Red cabbage and iskender salad', 3265, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (72, 'Peanut and parsnip soup', 3205, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (73, 'Chickpea and pancetta pasta', 2625, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (74, 'Pasta and polenta pizza', 1592, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (75, 'Cauliflower and crab madras', 2808, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (76, 'Sweetcorn and feta penne', 4151, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (77, 'Chilli and bresaola pasta', 2360, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (78, 'Celery and mushroom salad', 513, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (79, 'Aubergine and mushroom sushi', 5249, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (80, 'Okra and spinach stir fry', 1844, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (81, 'Leek and ham pizza', 1061, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (82, 'Boar and juniper berry salad', 4415, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (83, 'Leek and vermicelli soup', 5532, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (84, 'Beetroot and spinach fritters', 6673, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (85, 'Dolcelatte and honey pizza', 1914, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (86, 'Rosemary and toenjang salad', 1756, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (87, 'Potato and garlic pie', 5070, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (88, 'Haddock and napolitana salad', 2359, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (89, 'Hazelnut and vinegar salad', 5758, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (90, 'Peppercorn and tubetti penne', 2094, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (91, 'Chicken and fregola fusilli', 5431, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (92, 'Salmon and grouse toastie', 550, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (93, 'Lamb and duck skewers', 4947, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (94, 'Steak and celery soup', 1006, 3, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (95, 'Fish and goat stew', 1228, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (96, 'Radiatori and bulgur wheat salad', 5432, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (97, 'Yam and dulse salad', 4501, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (98, 'Pepper and kiwi fruit dip', 910, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (99, 'Italian seasoning and cider vinegar salad', 5082, 2, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (100, 'Almond and licorice salad', 3875, 1, false);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (101, 'Chilli and mango pizza', 3530, 2, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (102, 'Stilton and cheese dumplings', 5576, 3, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (103, 'Raisin and avocado salad', 2964, 1, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (104, 'Coconut and egg curry', 3696, 3, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (105, 'Courgette and apple soup', 2213, 1, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (106, 'Ugli fruit and caper salad', 3494, 3, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (107, 'Cheese and coconut bread', 6256, 1, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (108, 'Mushroom and egg maki', 4351, 2, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (109, 'Yam and cauliflower stir fry', 6758, 2, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (110, 'Cauliflower and spring onion salad', 6030, 2, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (111, 'Pesto and aubergine fusilli', 3852, 3, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (112, 'Mushroom and squash gnocchi', 6000, 2, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (113, 'Tofu and jackfruit salad', 1579, 3, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (114, 'Chilli and daikon fritters', 1717, 3, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (115, 'Mango and cabbage soup', 450, 3, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (116, 'Chickpea and cheddar toastie', 4854, 3, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (117, 'Mozzarella and potato skewers', 1268, 2, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (118, 'Squash and cauliflower vindaloo', 6341, 2, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (119, 'Peach and chestnut salad', 4525, 3, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (120, 'Dill and sage salad', 3700, 3, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (121, 'Wasabi and artichoke stir fry', 4278, 2, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (122, 'Peppercorn and tomato fusilli', 5841, 2, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (123, 'Bean and yoghurt soup', 1400, 3, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (124, 'Tamarind and mustard soup', 1227, 2, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (125, 'Tofu and mushroom sausages', 3077, 1, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (126, 'Aubergine and tofu sushi', 2188, 1, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (127, 'Thyme and longan salad', 1789, 3, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (128, 'Anise and banana vindaloo', 661, 3, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (129, 'Mushroom and potato curry', 5925, 2, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (130, 'Courgette and spring onion fritters', 6557, 3, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (131, 'Emmental and melon salad', 2279, 1, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (132, 'Pesto and potato pizza', 5154, 3, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (133, 'Clementine and pumpkin madras', 5233, 2, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (134, 'Brie and courgette salad', 3979, 1, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (135, 'Cardamom and apple gyoza', 235, 3, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (136, 'Peppercorn and leek parcels', 6826, 2, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (137, 'Rye and tea bread', 1486, 2, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (138, 'Potato and kale pie', 5850, 2, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (139, 'Pepper and parsnip casserole', 1575, 1, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (140, 'Burnet and egg salad', 7054, 2, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (141, 'Leek and potato soup', 6723, 3, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (142, 'Cabbage and sweetcorn dumplings', 4966, 3, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (143, 'Cheese and chickpea parcels', 5617, 2, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (144, 'Mushroom and cauliflower madras', 5102, 1, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (145, 'Basil and cardamom bread', 6593, 3, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (146, 'Chamomile and kale stir fry', 4513, 2, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (147, 'Chickpea and dolcelatte penne', 4940, 2, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (148, 'Mayonnaise and mushroom dip', 4561, 1, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (149, 'Samphire and star fruit salad', 5978, 2, true);
insert into recipes (id, name, pre_time, difficulty, vegetarian) values (150, 'Ricotta salad with garlic dressing', 351, 3, true);
insert into recipe_rating (recipe_id, rating) values (109, 1);
insert into recipe_rating (recipe_id, rating) values (22, 5);
insert into recipe_rating (recipe_id, rating) values (131, 4);
insert into recipe_rating (recipe_id, rating) values (18, 5);
insert into recipe_rating (recipe_id, rating) values (13, 2);
insert into recipe_rating (recipe_id, rating) values (148, 3);
insert into recipe_rating (recipe_id, rating) values (40, 2);
insert into recipe_rating (recipe_id, rating) values (57, 4);
insert into recipe_rating (recipe_id, rating) values (118, 3);
insert into recipe_rating (recipe_id, rating) values (140, 3);
insert into recipe_rating (recipe_id, rating) values (15, 5);
insert into recipe_rating (recipe_id, rating) values (16, 1);
insert into recipe_rating (recipe_id, rating) values (144, 2);
insert into recipe_rating (recipe_id, rating) values (29, 1);
insert into recipe_rating (recipe_id, rating) values (15, 3);
insert into recipe_rating (recipe_id, rating) values (139, 3);
insert into recipe_rating (recipe_id, rating) values (122, 3);
insert into recipe_rating (recipe_id, rating) values (58, 3);
insert into recipe_rating (recipe_id, rating) values (136, 4);
insert into recipe_rating (recipe_id, rating) values (110, 5);
insert into recipe_rating (recipe_id, rating) values (1, 4);
insert into recipe_rating (recipe_id, rating) values (17, 4);
insert into recipe_rating (recipe_id, rating) values (11, 5);
insert into recipe_rating (recipe_id, rating) values (52, 3);
insert into recipe_rating (recipe_id, rating) values (142, 1);
insert into recipe_rating (recipe_id, rating) values (72, 1);
insert into recipe_rating (recipe_id, rating) values (56, 5);
insert into recipe_rating (recipe_id, rating) values (105, 1);
insert into recipe_rating (recipe_id, rating) values (70, 1);
insert into recipe_rating (recipe_id, rating) values (74, 5);
insert into recipe_rating (recipe_id, rating) values (32, 4);
insert into recipe_rating (recipe_id, rating) values (131, 2);
insert into recipe_rating (recipe_id, rating) values (124, 5);
insert into recipe_rating (recipe_id, rating) values (47, 5);
insert into recipe_rating (recipe_id, rating) values (126, 3);
insert into recipe_rating (recipe_id, rating) values (143, 3);
insert into recipe_rating (recipe_id, rating) values (19, 1);
insert into recipe_rating (recipe_id, rating) values (77, 1);
insert into recipe_rating (recipe_id, rating) values (2, 5);
insert into recipe_rating (recipe_id, rating) values (68, 4);
insert into recipe_rating (recipe_id, rating) values (69, 2);
insert into recipe_rating (recipe_id, rating) values (49, 3);
insert into recipe_rating (recipe_id, rating) values (119, 2);
insert into recipe_rating (recipe_id, rating) values (144, 2);
insert into recipe_rating (recipe_id, rating) values (28, 1);
insert into recipe_rating (recipe_id, rating) values (142, 4);
insert into recipe_rating (recipe_id, rating) values (24, 1);
insert into recipe_rating (recipe_id, rating) values (38, 2);
insert into recipe_rating (recipe_id, rating) values (43, 1);
insert into recipe_rating (recipe_id, rating) values (28, 4);
insert into recipe_rating (recipe_id, rating) values (2, 4);
insert into recipe_rating (recipe_id, rating) values (38, 4);
insert into recipe_rating (recipe_id, rating) values (88, 1);
insert into recipe_rating (recipe_id, rating) values (1, 1);
insert into recipe_rating (recipe_id, rating) values (34, 3);
insert into recipe_rating (recipe_id, rating) values (18, 5);
insert into recipe_rating (recipe_id, rating) values (39, 5);
insert into recipe_rating (recipe_id, rating) values (35, 2);
insert into recipe_rating (recipe_id, rating) values (61, 4);
insert into recipe_rating (recipe_id, rating) values (86, 4);
insert into recipe_rating (recipe_id, rating) values (92, 4);
insert into recipe_rating (recipe_id, rating) values (126, 3);
insert into recipe_rating (recipe_id, rating) values (144, 2);
insert into recipe_rating (recipe_id, rating) values (42, 3);
insert into recipe_rating (recipe_id, rating) values (115, 4);
insert into recipe_rating (recipe_id, rating) values (61, 3);
insert into recipe_rating (recipe_id, rating) values (123, 4);
insert into recipe_rating (recipe_id, rating) values (4, 4);
insert into recipe_rating (recipe_id, rating) values (1, 5);
insert into recipe_rating (recipe_id, rating) values (97, 4);
insert into recipe_rating (recipe_id, rating) values (109, 2);
insert into recipe_rating (recipe_id, rating) values (71, 1);
insert into recipe_rating (recipe_id, rating) values (21, 1);
insert into recipe_rating (recipe_id, rating) values (44, 3);
insert into recipe_rating (recipe_id, rating) values (39, 2);
insert into recipe_rating (recipe_id, rating) values (19, 3);
insert into recipe_rating (recipe_id, rating) values (1, 3);
insert into recipe_rating (recipe_id, rating) values (112, 1);
insert into recipe_rating (recipe_id, rating) values (47, 4);
insert into recipe_rating (recipe_id, rating) values (103, 5);
insert into recipe_rating (recipe_id, rating) values (77, 2);
insert into recipe_rating (recipe_id, rating) values (74, 1);
insert into recipe_rating (recipe_id, rating) values (122, 2);
insert into recipe_rating (recipe_id, rating) values (131, 2);
insert into recipe_rating (recipe_id, rating) values (10, 4);
insert into recipe_rating (recipe_id, rating) values (35, 4);
insert into recipe_rating (recipe_id, rating) values (49, 1);
insert into recipe_rating (recipe_id, rating) values (44, 2);
insert into recipe_rating (recipe_id, rating) values (83, 5);
insert into recipe_rating (recipe_id, rating) values (24, 2);
insert into recipe_rating (recipe_id, rating) values (34, 3);
insert into recipe_rating (recipe_id, rating) values (68, 1);
insert into recipe_rating (recipe_id, rating) values (23, 2);
insert into recipe_rating (recipe_id, rating) values (73, 4);
insert into recipe_rating (recipe_id, rating) values (44, 4);
insert into recipe_rating (recipe_id, rating) values (30, 2);
insert into recipe_rating (recipe_id, rating) values (89, 1);
insert into recipe_rating (recipe_id, rating) values (122, 3);
insert into recipe_rating (recipe_id, rating) values (5, 3);
insert into recipe_rating (recipe_id, rating) values (148, 5);
insert into recipe_rating (recipe_id, rating) values (143, 5);
insert into recipe_rating (recipe_id, rating) values (135, 2);
insert into recipe_rating (recipe_id, rating) values (80, 4);
insert into recipe_rating (recipe_id, rating) values (66, 1);
insert into recipe_rating (recipe_id, rating) values (28, 1);
insert into recipe_rating (recipe_id, rating) values (124, 5);
insert into recipe_rating (recipe_id, rating) values (43, 3);
insert into recipe_rating (recipe_id, rating) values (78, 3);
insert into recipe_rating (recipe_id, rating) values (102, 5);
insert into recipe_rating (recipe_id, rating) values (70, 1);
insert into recipe_rating (recipe_id, rating) values (106, 2);
insert into recipe_rating (recipe_id, rating) values (103, 1);
insert into recipe_rating (recipe_id, rating) values (62, 4);
insert into recipe_rating (recipe_id, rating) values (37, 5);
insert into recipe_rating (recipe_id, rating) values (144, 2);
insert into recipe_rating (recipe_id, rating) values (39, 3);
insert into recipe_rating (recipe_id, rating) values (45, 2);
insert into recipe_rating (recipe_id, rating) values (69, 4);
insert into recipe_rating (recipe_id, rating) values (95, 1);
insert into recipe_rating (recipe_id, rating) values (53, 2);
insert into recipe_rating (recipe_id, rating) values (72, 1);
insert into recipe_rating (recipe_id, rating) values (150, 3);
insert into recipe_rating (recipe_id, rating) values (18, 4);
insert into recipe_rating (recipe_id, rating) values (99, 3);
insert into recipe_rating (recipe_id, rating) values (14, 4);
insert into recipe_rating (recipe_id, rating) values (12, 2);
insert into recipe_rating (recipe_id, rating) values (141, 2);
insert into recipe_rating (recipe_id, rating) values (108, 1);
insert into recipe_rating (recipe_id, rating) values (149, 4);
insert into recipe_rating (recipe_id, rating) values (19, 5);
insert into recipe_rating (recipe_id, rating) values (121, 3);
insert into recipe_rating (recipe_id, rating) values (23, 3);
insert into recipe_rating (recipe_id, rating) values (37, 5);
insert into recipe_rating (recipe_id, rating) values (37, 1);
insert into recipe_rating (recipe_id, rating) values (46, 1);
insert into recipe_rating (recipe_id, rating) values (135, 1);
insert into recipe_rating (recipe_id, rating) values (1, 4);
insert into recipe_rating (recipe_id, rating) values (58, 1);
insert into recipe_rating (recipe_id, rating) values (4, 1);
insert into recipe_rating (recipe_id, rating) values (89, 3);
insert into recipe_rating (recipe_id, rating) values (60, 1);
insert into recipe_rating (recipe_id, rating) values (130, 5);
insert into recipe_rating (recipe_id, rating) values (1, 4);
insert into recipe_rating (recipe_id, rating) values (36, 3);
insert into recipe_rating (recipe_id, rating) values (30, 3);
insert into recipe_rating (recipe_id, rating) values (24, 3);
insert into recipe_rating (recipe_id, rating) values (4, 2);
insert into recipe_rating (recipe_id, rating) values (114, 4);
insert into recipe_rating (recipe_id, rating) values (69, 1);
insert into recipe_rating (recipe_id, rating) values (13, 3);
insert into recipe_rating (recipe_id, rating) values (58, 5);
insert into recipe_rating (recipe_id, rating) values (55, 1);
insert into recipe_rating (recipe_id, rating) values (23, 2);
insert into recipe_rating (recipe_id, rating) values (8, 5);
insert into recipe_rating (recipe_id, rating) values (52, 1);
insert into recipe_rating (recipe_id, rating) values (10, 3);
insert into recipe_rating (recipe_id, rating) values (52, 2);
insert into recipe_rating (recipe_id, rating) values (54, 5);
insert into recipe_rating (recipe_id, rating) values (80, 2);
insert into recipe_rating (recipe_id, rating) values (50, 4);
insert into recipe_rating (recipe_id, rating) values (91, 5);
insert into recipe_rating (recipe_id, rating) values (47, 5);
insert into recipe_rating (recipe_id, rating) values (130, 5);
insert into recipe_rating (recipe_id, rating) values (104, 2);
insert into recipe_rating (recipe_id, rating) values (53, 2);
insert into recipe_rating (recipe_id, rating) values (2, 1);
insert into recipe_rating (recipe_id, rating) values (15, 1);
insert into recipe_rating (recipe_id, rating) values (105, 4);
insert into recipe_rating (recipe_id, rating) values (20, 1);
insert into recipe_rating (recipe_id, rating) values (63, 5);
insert into recipe_rating (recipe_id, rating) values (119, 4);
insert into recipe_rating (recipe_id, rating) values (144, 4);
insert into recipe_rating (recipe_id, rating) values (115, 5);
insert into recipe_rating (recipe_id, rating) values (62, 4);
insert into recipe_rating (recipe_id, rating) values (135, 3);
insert into recipe_rating (recipe_id, rating) values (52, 2);
insert into recipe_rating (recipe_id, rating) values (47, 1);
insert into recipe_rating (recipe_id, rating) values (16, 5);
insert into recipe_rating (recipe_id, rating) values (69, 4);
insert into recipe_rating (recipe_id, rating) values (130, 2);
insert into recipe_rating (recipe_id, rating) values (58, 1);
insert into recipe_rating (recipe_id, rating) values (146, 1);
insert into recipe_rating (recipe_id, rating) values (142, 1);
insert into recipe_rating (recipe_id, rating) values (71, 4);
insert into recipe_rating (recipe_id, rating) values (102, 3);
insert into recipe_rating (recipe_id, rating) values (108, 4);
insert into recipe_rating (recipe_id, rating) values (47, 1);
insert into recipe_rating (recipe_id, rating) values (63, 3);
insert into recipe_rating (recipe_id, rating) values (100, 3);
insert into recipe_rating (recipe_id, rating) values (112, 1);
insert into recipe_rating (recipe_id, rating) values (88, 1);
insert into recipe_rating (recipe_id, rating) values (19, 3);
insert into recipe_rating (recipe_id, rating) values (67, 3);
insert into recipe_rating (recipe_id, rating) values (132, 4);
insert into recipe_rating (recipe_id, rating) values (135, 5);
insert into recipe_rating (recipe_id, rating) values (117, 3);
insert into recipe_rating (recipe_id, rating) values (36, 5);
insert into recipe_rating (recipe_id, rating) values (17, 5);
insert into recipe_rating (recipe_id, rating) values (25, 4);
insert into recipe_rating (recipe_id, rating) values (115, 2);
insert into recipe_rating (recipe_id, rating) values (142, 5);
insert into recipe_rating (recipe_id, rating) values (81, 1);
insert into recipe_rating (recipe_id, rating) values (9, 2);
insert into recipe_rating (recipe_id, rating) values (110, 3);
insert into recipe_rating (recipe_id, rating) values (38, 4);
insert into recipe_rating (recipe_id, rating) values (97, 2);
insert into recipe_rating (recipe_id, rating) values (42, 5);
insert into recipe_rating (recipe_id, rating) values (46, 3);
insert into recipe_rating (recipe_id, rating) values (42, 1);
insert into recipe_rating (recipe_id, rating) values (10, 3);
insert into recipe_rating (recipe_id, rating) values (26, 4);
insert into recipe_rating (recipe_id, rating) values (64, 2);
insert into recipe_rating (recipe_id, rating) values (21, 1);
insert into recipe_rating (recipe_id, rating) values (97, 2);
insert into recipe_rating (recipe_id, rating) values (70, 1);
insert into recipe_rating (recipe_id, rating) values (116, 5);
insert into recipe_rating (recipe_id, rating) values (112, 2);
insert into recipe_rating (recipe_id, rating) values (121, 4);
insert into recipe_rating (recipe_id, rating) values (41, 4);
insert into recipe_rating (recipe_id, rating) values (115, 4);
insert into recipe_rating (recipe_id, rating) values (48, 3);
insert into recipe_rating (recipe_id, rating) values (118, 4);
insert into recipe_rating (recipe_id, rating) values (100, 1);
insert into recipe_rating (recipe_id, rating) values (55, 5);
insert into recipe_rating (recipe_id, rating) values (1, 1);
insert into recipe_rating (recipe_id, rating) values (99, 1);
insert into recipe_rating (recipe_id, rating) values (70, 4);
insert into recipe_rating (recipe_id, rating) values (131, 1);
insert into recipe_rating (recipe_id, rating) values (27, 1);
insert into recipe_rating (recipe_id, rating) values (102, 5);
insert into recipe_rating (recipe_id, rating) values (25, 5);
insert into recipe_rating (recipe_id, rating) values (36, 3);
insert into recipe_rating (recipe_id, rating) values (120, 1);
insert into recipe_rating (recipe_id, rating) values (142, 4);
insert into recipe_rating (recipe_id, rating) values (75, 3);
insert into recipe_rating (recipe_id, rating) values (56, 2);
insert into recipe_rating (recipe_id, rating) values (76, 3);
insert into recipe_rating (recipe_id, rating) values (70, 3);
insert into recipe_rating (recipe_id, rating) values (49, 1);
insert into recipe_rating (recipe_id, rating) values (141, 4);
insert into recipe_rating (recipe_id, rating) values (109, 2);
insert into recipe_rating (recipe_id, rating) values (90, 4);
insert into recipe_rating (recipe_id, rating) values (24, 1);
insert into recipe_rating (recipe_id, rating) values (144, 5);
insert into recipe_rating (recipe_id, rating) values (79, 2);
insert into recipe_rating (recipe_id, rating) values (150, 4);
insert into recipe_rating (recipe_id, rating) values (149, 1);
insert into recipe_rating (recipe_id, rating) values (9, 4);
insert into recipe_rating (recipe_id, rating) values (100, 1);
insert into recipe_rating (recipe_id, rating) values (14, 1);
insert into recipe_rating (recipe_id, rating) values (55, 3);
insert into recipe_rating (recipe_id, rating) values (94, 3);
insert into recipe_rating (recipe_id, rating) values (104, 5);
insert into recipe_rating (recipe_id, rating) values (130, 1);
insert into recipe_rating (recipe_id, rating) values (138, 4);
insert into recipe_rating (recipe_id, rating) values (101, 2);
insert into recipe_rating (recipe_id, rating) values (18, 4);
insert into recipe_rating (recipe_id, rating) values (108, 3);
insert into recipe_rating (recipe_id, rating) values (112, 1);
insert into recipe_rating (recipe_id, rating) values (102, 5);
insert into recipe_rating (recipe_id, rating) values (32, 4);
insert into recipe_rating (recipe_id, rating) values (92, 3);
insert into recipe_rating (recipe_id, rating) values (86, 3);
insert into recipe_rating (recipe_id, rating) values (148, 5);
insert into recipe_rating (recipe_id, rating) values (47, 2);
insert into recipe_rating (recipe_id, rating) values (143, 3);
insert into recipe_rating (recipe_id, rating) values (103, 1);
insert into recipe_rating (recipe_id, rating) values (7, 5);
insert into recipe_rating (recipe_id, rating) values (26, 1);
insert into recipe_rating (recipe_id, rating) values (36, 1);
insert into recipe_rating (recipe_id, rating) values (45, 2);
insert into recipe_rating (recipe_id, rating) values (51, 5);
insert into recipe_rating (recipe_id, rating) values (66, 2);
insert into recipe_rating (recipe_id, rating) values (58, 3);
insert into recipe_rating (recipe_id, rating) values (11, 5);
insert into recipe_rating (recipe_id, rating) values (8, 5);
insert into recipe_rating (recipe_id, rating) values (118, 4);
insert into recipe_rating (recipe_id, rating) values (136, 4);
insert into recipe_rating (recipe_id, rating) values (84, 1);
insert into recipe_rating (recipe_id, rating) values (89, 3);
insert into recipe_rating (recipe_id, rating) values (108, 5);
insert into recipe_rating (recipe_id, rating) values (72, 3);
insert into recipe_rating (recipe_id, rating) values (76, 2);
insert into recipe_rating (recipe_id, rating) values (128, 2);
insert into recipe_rating (recipe_id, rating) values (92, 4);
insert into recipe_rating (recipe_id, rating) values (95, 2);
insert into recipe_rating (recipe_id, rating) values (143, 2);
insert into recipe_rating (recipe_id, rating) values (129, 4);
insert into recipe_rating (recipe_id, rating) values (109, 2);
insert into recipe_rating (recipe_id, rating) values (22, 1);
insert into recipe_rating (recipe_id, rating) values (139, 4);
insert into recipe_rating (recipe_id, rating) values (11, 4);
insert into recipe_rating (recipe_id, rating) values (42, 3);
insert into recipe_rating (recipe_id, rating) values (109, 1);
insert into recipe_rating (recipe_id, rating) values (37, 1);
insert into recipe_rating (recipe_id, rating) values (140, 4);
insert into recipe_rating (recipe_id, rating) values (31, 4);
insert into recipe_rating (recipe_id, rating) values (81, 3);
insert into recipe_rating (recipe_id, rating) values (9, 4);
insert into recipe_rating (recipe_id, rating) values (52, 4);
insert into recipe_rating (recipe_id, rating) values (72, 5);
insert into recipe_rating (recipe_id, rating) values (129, 5);
insert into recipe_rating (recipe_id, rating) values (6, 2);
insert into recipe_rating (recipe_id, rating) values (130, 5);
insert into recipe_rating (recipe_id, rating) values (106, 3);
insert into recipe_rating (recipe_id, rating) values (9, 4);
insert into recipe_rating (recipe_id, rating) values (128, 3);
insert into recipe_rating (recipe_id, rating) values (68, 4);
insert into recipe_rating (recipe_id, rating) values (140, 3);
insert into recipe_rating (recipe_id, rating) values (12, 4);
insert into recipe_rating (recipe_id, rating) values (134, 1);
insert into recipe_rating (recipe_id, rating) values (5, 1);
insert into recipe_rating (recipe_id, rating) values (79, 5);
insert into recipe_rating (recipe_id, rating) values (129, 1);
insert into recipe_rating (recipe_id, rating) values (21, 3);
insert into recipe_rating (recipe_id, rating) values (116, 1);
insert into recipe_rating (recipe_id, rating) values (63, 4);
insert into recipe_rating (recipe_id, rating) values (49, 3);
insert into recipe_rating (recipe_id, rating) values (20, 4);
insert into recipe_rating (recipe_id, rating) values (27, 4);
insert into recipe_rating (recipe_id, rating) values (85, 2);
insert into recipe_rating (recipe_id, rating) values (99, 1);
insert into recipe_rating (recipe_id, rating) values (40, 1);
insert into recipe_rating (recipe_id, rating) values (81, 1);
insert into recipe_rating (recipe_id, rating) values (106, 4);
insert into recipe_rating (recipe_id, rating) values (81, 5);
insert into recipe_rating (recipe_id, rating) values (100, 1);
insert into recipe_rating (recipe_id, rating) values (137, 4);
insert into recipe_rating (recipe_id, rating) values (60, 4);
insert into recipe_rating (recipe_id, rating) values (71, 2);
insert into recipe_rating (recipe_id, rating) values (139, 2);
insert into recipe_rating (recipe_id, rating) values (16, 3);
insert into recipe_rating (recipe_id, rating) values (116, 5);
insert into recipe_rating (recipe_id, rating) values (93, 2);
insert into recipe_rating (recipe_id, rating) values (62, 4);
insert into recipe_rating (recipe_id, rating) values (99, 1);
insert into recipe_rating (recipe_id, rating) values (45, 1);
insert into recipe_rating (recipe_id, rating) values (21, 5);
insert into recipe_rating (recipe_id, rating) values (85, 2);
insert into recipe_rating (recipe_id, rating) values (147, 1);
insert into recipe_rating (recipe_id, rating) values (79, 1);
insert into recipe_rating (recipe_id, rating) values (89, 5);
insert into recipe_rating (recipe_id, rating) values (137, 1);
insert into recipe_rating (recipe_id, rating) values (57, 3);
insert into recipe_rating (recipe_id, rating) values (120, 5);
insert into recipe_rating (recipe_id, rating) values (32, 4);
insert into recipe_rating (recipe_id, rating) values (31, 4);
insert into recipe_rating (recipe_id, rating) values (9, 2);
insert into recipe_rating (recipe_id, rating) values (117, 1);
insert into recipe_rating (recipe_id, rating) values (67, 1);
insert into recipe_rating (recipe_id, rating) values (128, 3);
insert into recipe_rating (recipe_id, rating) values (94, 3);
insert into recipe_rating (recipe_id, rating) values (99, 5);
insert into recipe_rating (recipe_id, rating) values (110, 1);
insert into recipe_rating (recipe_id, rating) values (48, 2);
insert into recipe_rating (recipe_id, rating) values (15, 5);
insert into recipe_rating (recipe_id, rating) values (131, 1);
insert into recipe_rating (recipe_id, rating) values (143, 2);
insert into recipe_rating (recipe_id, rating) values (84, 3);
insert into recipe_rating (recipe_id, rating) values (109, 4);
insert into recipe_rating (recipe_id, rating) values (36, 5);
insert into recipe_rating (recipe_id, rating) values (69, 4);
insert into recipe_rating (recipe_id, rating) values (96, 5);
insert into recipe_rating (recipe_id, rating) values (32, 2);
insert into recipe_rating (recipe_id, rating) values (129, 4);
insert into recipe_rating (recipe_id, rating) values (49, 3);
insert into recipe_rating (recipe_id, rating) values (8, 2);
insert into recipe_rating (recipe_id, rating) values (100, 1);
insert into recipe_rating (recipe_id, rating) values (116, 5);
insert into recipe_rating (recipe_id, rating) values (122, 2);
insert into recipe_rating (recipe_id, rating) values (108, 3);
insert into recipe_rating (recipe_id, rating) values (97, 1);
insert into recipe_rating (recipe_id, rating) values (131, 2);
insert into recipe_rating (recipe_id, rating) values (98, 2);
insert into recipe_rating (recipe_id, rating) values (36, 4);
insert into recipe_rating (recipe_id, rating) values (28, 3);
insert into recipe_rating (recipe_id, rating) values (78, 2);
insert into recipe_rating (recipe_id, rating) values (38, 5);
insert into recipe_rating (recipe_id, rating) values (16, 4);
insert into recipe_rating (recipe_id, rating) values (141, 2);
insert into recipe_rating (recipe_id, rating) values (11, 1);
insert into recipe_rating (recipe_id, rating) values (28, 4);
insert into recipe_rating (recipe_id, rating) values (31, 2);
insert into recipe_rating (recipe_id, rating) values (137, 2);
insert into recipe_rating (recipe_id, rating) values (67, 2);
insert into recipe_rating (recipe_id, rating) values (106, 3);
insert into recipe_rating (recipe_id, rating) values (109, 3);
insert into recipe_rating (recipe_id, rating) values (29, 3);
insert into recipe_rating (recipe_id, rating) values (57, 5);
insert into recipe_rating (recipe_id, rating) values (144, 4);
insert into recipe_rating (recipe_id, rating) values (63, 4);
insert into recipe_rating (recipe_id, rating) values (122, 4);
insert into recipe_rating (recipe_id, rating) values (114, 3);
insert into recipe_rating (recipe_id, rating) values (82, 2);
insert into recipe_rating (recipe_id, rating) values (29, 5);
insert into recipe_rating (recipe_id, rating) values (41, 2);
insert into recipe_rating (recipe_id, rating) values (46, 4);
insert into recipe_rating (recipe_id, rating) values (2, 4);
insert into recipe_rating (recipe_id, rating) values (136, 1);
insert into recipe_rating (recipe_id, rating) values (24, 3);
insert into recipe_rating (recipe_id, rating) values (137, 1);
insert into recipe_rating (recipe_id, rating) values (46, 2);
insert into recipe_rating (recipe_id, rating) values (52, 2);
insert into recipe_rating (recipe_id, rating) values (109, 3);
insert into recipe_rating (recipe_id, rating) values (38, 3);
insert into recipe_rating (recipe_id, rating) values (123, 1);
insert into recipe_rating (recipe_id, rating) values (129, 3);
insert into recipe_rating (recipe_id, rating) values (128, 2);
insert into recipe_rating (recipe_id, rating) values (75, 3);
insert into recipe_rating (recipe_id, rating) values (46, 4);
insert into recipe_rating (recipe_id, rating) values (32, 2);
insert into recipe_rating (recipe_id, rating) values (94, 5);
insert into recipe_rating (recipe_id, rating) values (76, 2);
insert into recipe_rating (recipe_id, rating) values (62, 4);
insert into recipe_rating (recipe_id, rating) values (51, 5);
insert into recipe_rating (recipe_id, rating) values (118, 3);
insert into recipe_rating (recipe_id, rating) values (1, 3);
insert into recipe_rating (recipe_id, rating) values (53, 1);
insert into recipe_rating (recipe_id, rating) values (99, 4);
insert into recipe_rating (recipe_id, rating) values (97, 4);
insert into recipe_rating (recipe_id, rating) values (3, 5);
insert into recipe_rating (recipe_id, rating) values (50, 3);
insert into recipe_rating (recipe_id, rating) values (113, 5);
insert into recipe_rating (recipe_id, rating) values (94, 5);
insert into recipe_rating (recipe_id, rating) values (28, 1);
insert into recipe_rating (recipe_id, rating) values (45, 1);
insert into recipe_rating (recipe_id, rating) values (46, 1);
insert into recipe_rating (recipe_id, rating) values (126, 5);
insert into recipe_rating (recipe_id, rating) values (144, 4);
insert into recipe_rating (recipe_id, rating) values (127, 1);
insert into recipe_rating (recipe_id, rating) values (98, 2);
insert into recipe_rating (recipe_id, rating) values (41, 5);
insert into recipe_rating (recipe_id, rating) values (141, 2);
insert into recipe_rating (recipe_id, rating) values (94, 2);
insert into recipe_rating (recipe_id, rating) values (6, 4);
insert into recipe_rating (recipe_id, rating) values (8, 4);
insert into recipe_rating (recipe_id, rating) values (103, 1);
insert into recipe_rating (recipe_id, rating) values (3, 2);
insert into recipe_rating (recipe_id, rating) values (29, 3);
insert into recipe_rating (recipe_id, rating) values (127, 5);
insert into recipe_rating (recipe_id, rating) values (110, 1);
insert into recipe_rating (recipe_id, rating) values (121, 5);
insert into recipe_rating (recipe_id, rating) values (95, 3);
insert into recipe_rating (recipe_id, rating) values (62, 4);
insert into recipe_rating (recipe_id, rating) values (69, 4);
insert into recipe_rating (recipe_id, rating) values (22, 1);
insert into recipe_rating (recipe_id, rating) values (26, 5);
insert into recipe_rating (recipe_id, rating) values (12, 2);
insert into recipe_rating (recipe_id, rating) values (91, 1);
insert into recipe_rating (recipe_id, rating) values (41, 1);
insert into recipe_rating (recipe_id, rating) values (89, 3);
insert into recipe_rating (recipe_id, rating) values (100, 1);
insert into recipe_rating (recipe_id, rating) values (7, 4);
insert into recipe_rating (recipe_id, rating) values (66, 3);
insert into recipe_rating (recipe_id, rating) values (11, 2);
insert into recipe_rating (recipe_id, rating) values (27, 4);
insert into recipe_rating (recipe_id, rating) values (12, 4);
insert into recipe_rating (recipe_id, rating) values (65, 5);
insert into recipe_rating (recipe_id, rating) values (66, 3);
insert into recipe_rating (recipe_id, rating) values (126, 4);
insert into recipe_rating (recipe_id, rating) values (109, 2);
insert into recipe_rating (recipe_id, rating) values (88, 5);
insert into recipe_rating (recipe_id, rating) values (11, 5);
insert into recipe_rating (recipe_id, rating) values (78, 5);
insert into recipe_rating (recipe_id, rating) values (125, 5);
insert into recipe_rating (recipe_id, rating) values (109, 5);
insert into recipe_rating (recipe_id, rating) values (58, 1);
insert into recipe_rating (recipe_id, rating) values (118, 3);
insert into recipe_rating (recipe_id, rating) values (54, 4);
insert into recipe_rating (recipe_id, rating) values (31, 5);
insert into recipe_rating (recipe_id, rating) values (75, 5);
insert into recipe_rating (recipe_id, rating) values (105, 5);
insert into recipe_rating (recipe_id, rating) values (75, 2);
insert into recipe_rating (recipe_id, rating) values (57, 2);
insert into recipe_rating (recipe_id, rating) values (2, 1);
insert into recipe_rating (recipe_id, rating) values (111, 3);
insert into recipe_rating (recipe_id, rating) values (137, 2);
insert into recipe_rating (recipe_id, rating) values (12, 2);
insert into recipe_rating (recipe_id, rating) values (56, 1);
insert into recipe_rating (recipe_id, rating) values (18, 3);
insert into recipe_rating (recipe_id, rating) values (119, 3);
insert into recipe_rating (recipe_id, rating) values (33, 3);
insert into recipe_rating (recipe_id, rating) values (125, 3);
insert into recipe_rating (recipe_id, rating) values (142, 3);
insert into recipe_rating (recipe_id, rating) values (123, 1);
insert into recipe_rating (recipe_id, rating) values (6, 5);
insert into recipe_rating (recipe_id, rating) values (57, 1);
insert into recipe_rating (recipe_id, rating) values (121, 2);
insert into recipe_rating (recipe_id, rating) values (42, 2);
insert into recipe_rating (recipe_id, rating) values (99, 4);
insert into recipe_rating (recipe_id, rating) values (150, 5);
insert into recipe_rating (recipe_id, rating) values (123, 2);
insert into recipe_rating (recipe_id, rating) values (123, 4);
insert into recipe_rating (recipe_id, rating) values (77, 2);
insert into recipe_rating (recipe_id, rating) values (92, 5);
insert into recipe_rating (recipe_id, rating) values (54, 3);
insert into recipe_rating (recipe_id, rating) values (124, 2);
insert into recipe_rating (recipe_id, rating) values (95, 2);
insert into recipe_rating (recipe_id, rating) values (5, 5);
insert into recipe_rating (recipe_id, rating) values (138, 3);
insert into recipe_rating (recipe_id, rating) values (73, 2);
insert into recipe_rating (recipe_id, rating) values (147, 1);
insert into recipe_rating (recipe_id, rating) values (95, 4);
insert into recipe_rating (recipe_id, rating) values (123, 1);
insert into recipe_rating (recipe_id, rating) values (103, 2);
insert into recipe_rating (recipe_id, rating) values (115, 2);
insert into recipe_rating (recipe_id, rating) values (71, 3);
insert into recipe_rating (recipe_id, rating) values (15, 5);
insert into recipe_rating (recipe_id, rating) values (79, 4);
insert into recipe_rating (recipe_id, rating) values (51, 2);
insert into recipe_rating (recipe_id, rating) values (136, 1);
insert into recipe_rating (recipe_id, rating) values (120, 3);
insert into recipe_rating (recipe_id, rating) values (91, 5);
insert into recipe_rating (recipe_id, rating) values (150, 2);
insert into recipe_rating (recipe_id, rating) values (110, 2);
insert into recipe_rating (recipe_id, rating) values (146, 5);
insert into recipe_rating (recipe_id, rating) values (87, 4);
insert into recipe_rating (recipe_id, rating) values (117, 1);
insert into recipe_rating (recipe_id, rating) values (131, 2);
insert into recipe_rating (recipe_id, rating) values (113, 3);
insert into recipe_rating (recipe_id, rating) values (46, 2);
insert into recipe_rating (recipe_id, rating) values (108, 2);
insert into recipe_rating (recipe_id, rating) values (32, 3);
insert into recipe_rating (recipe_id, rating) values (131, 3);
insert into recipe_rating (recipe_id, rating) values (54, 5);
insert into recipe_rating (recipe_id, rating) values (145, 4);
insert into recipe_rating (recipe_id, rating) values (15, 1);
insert into recipe_rating (recipe_id, rating) values (14, 1);
insert into recipe_rating (recipe_id, rating) values (44, 5);
insert into recipe_rating (recipe_id, rating) values (24, 1);
insert into recipe_rating (recipe_id, rating) values (119, 5);
insert into recipe_rating (recipe_id, rating) values (110, 4);
insert into recipe_rating (recipe_id, rating) values (63, 1);
insert into recipe_rating (recipe_id, rating) values (119, 4);
insert into recipe_rating (recipe_id, rating) values (49, 1);
insert into recipe_rating (recipe_id, rating) values (85, 2);
insert into recipe_rating (recipe_id, rating) values (32, 1);
insert into recipe_rating (recipe_id, rating) values (86, 5);
insert into recipe_rating (recipe_id, rating) values (24, 3);
insert into recipe_rating (recipe_id, rating) values (41, 5);
insert into recipe_rating (recipe_id, rating) values (12, 4);
insert into recipe_rating (recipe_id, rating) values (38, 4);
insert into recipe_rating (recipe_id, rating) values (25, 2);
insert into recipe_rating (recipe_id, rating) values (103, 5);
insert into recipe_rating (recipe_id, rating) values (38, 2);
insert into recipe_rating (recipe_id, rating) values (73, 5);
insert into recipe_rating (recipe_id, rating) values (64, 1);
insert into recipe_rating (recipe_id, rating) values (8, 4);
insert into recipe_rating (recipe_id, rating) values (112, 4);
insert into recipe_rating (recipe_id, rating) values (43, 1);
insert into recipe_rating (recipe_id, rating) values (72, 5);
insert into recipe_rating (recipe_id, rating) values (111, 2);
insert into recipe_rating (recipe_id, rating) values (125, 2);
insert into recipe_rating (recipe_id, rating) values (15, 2);
insert into recipe_rating (recipe_id, rating) values (103, 2);
insert into recipe_rating (recipe_id, rating) values (115, 5);
insert into recipe_rating (recipe_id, rating) values (75, 2);
insert into recipe_rating (recipe_id, rating) values (72, 1);
insert into recipe_rating (recipe_id, rating) values (26, 1);
insert into recipe_rating (recipe_id, rating) values (109, 1);
insert into recipe_rating (recipe_id, rating) values (20, 3);
insert into recipe_rating (recipe_id, rating) values (146, 5);
insert into recipe_rating (recipe_id, rating) values (70, 3);
insert into recipe_rating (recipe_id, rating) values (54, 5);
insert into recipe_rating (recipe_id, rating) values (1, 5);
insert into recipe_rating (recipe_id, rating) values (57, 3);
insert into recipe_rating (recipe_id, rating) values (112, 1);
insert into recipe_rating (recipe_id, rating) values (55, 1);
insert into recipe_rating (recipe_id, rating) values (124, 1);
insert into recipe_rating (recipe_id, rating) values (23, 1);
insert into recipe_rating (recipe_id, rating) values (89, 4);
insert into recipe_rating (recipe_id, rating) values (98, 5);
insert into recipe_rating (recipe_id, rating) values (18, 2);
insert into recipe_rating (recipe_id, rating) values (4, 4);
insert into recipe_rating (recipe_id, rating) values (67, 2);
insert into recipe_rating (recipe_id, rating) values (5, 3);
insert into recipe_rating (recipe_id, rating) values (82, 4);
insert into recipe_rating (recipe_id, rating) values (81, 4);
insert into recipe_rating (recipe_id, rating) values (137, 3);
insert into recipe_rating (recipe_id, rating) values (81, 3);
insert into recipe_rating (recipe_id, rating) values (13, 1);
insert into recipe_rating (recipe_id, rating) values (142, 4);
insert into recipe_rating (recipe_id, rating) values (42, 1);
insert into recipe_rating (recipe_id, rating) values (149, 2);
insert into recipe_rating (recipe_id, rating) values (104, 3);
insert into recipe_rating (recipe_id, rating) values (53, 3);
insert into recipe_rating (recipe_id, rating) values (29, 2);
insert into recipe_rating (recipe_id, rating) values (115, 1);
insert into recipe_rating (recipe_id, rating) values (60, 3);
insert into recipe_rating (recipe_id, rating) values (2, 3);
insert into recipe_rating (recipe_id, rating) values (19, 2);
insert into recipe_rating (recipe_id, rating) values (44, 2);
insert into recipe_rating (recipe_id, rating) values (147, 5);
insert into recipe_rating (recipe_id, rating) values (59, 1);
insert into recipe_rating (recipe_id, rating) values (62, 2);
insert into recipe_rating (recipe_id, rating) values (69, 3);
insert into recipe_rating (recipe_id, rating) values (125, 1);
insert into recipe_rating (recipe_id, rating) values (74, 3);
insert into recipe_rating (recipe_id, rating) values (132, 1);
insert into recipe_rating (recipe_id, rating) values (34, 3);
insert into recipe_rating (recipe_id, rating) values (71, 2);
insert into recipe_rating (recipe_id, rating) values (13, 3);
insert into recipe_rating (recipe_id, rating) values (23, 2);
insert into recipe_rating (recipe_id, rating) values (18, 2);
insert into recipe_rating (recipe_id, rating) values (95, 2);
insert into recipe_rating (recipe_id, rating) values (126, 5);
insert into recipe_rating (recipe_id, rating) values (10, 5);
insert into recipe_rating (recipe_id, rating) values (21, 1);
insert into recipe_rating (recipe_id, rating) values (66, 5);
insert into recipe_rating (recipe_id, rating) values (46, 5);
insert into recipe_rating (recipe_id, rating) values (150, 5);
insert into recipe_rating (recipe_id, rating) values (76, 5);
insert into recipe_rating (recipe_id, rating) values (5, 1);
insert into recipe_rating (recipe_id, rating) values (133, 1);
insert into recipe_rating (recipe_id, rating) values (65, 5);
insert into recipe_rating (recipe_id, rating) values (15, 2);
insert into recipe_rating (recipe_id, rating) values (61, 5);
insert into recipe_rating (recipe_id, rating) values (106, 1);
insert into recipe_rating (recipe_id, rating) values (16, 4);
insert into recipe_rating (recipe_id, rating) values (33, 5);
insert into recipe_rating (recipe_id, rating) values (108, 5);
insert into recipe_rating (recipe_id, rating) values (106, 3);
insert into recipe_rating (recipe_id, rating) values (27, 4);
insert into recipe_rating (recipe_id, rating) values (120, 3);
insert into recipe_rating (recipe_id, rating) values (11, 2);
insert into recipe_rating (recipe_id, rating) values (77, 2);
insert into recipe_rating (recipe_id, rating) values (128, 1);
insert into recipe_rating (recipe_id, rating) values (27, 3);
insert into recipe_rating (recipe_id, rating) values (118, 1);
insert into recipe_rating (recipe_id, rating) values (149, 4);
insert into recipe_rating (recipe_id, rating) values (106, 2);
insert into recipe_rating (recipe_id, rating) values (66, 5);
insert into recipe_rating (recipe_id, rating) values (119, 4);
insert into recipe_rating (recipe_id, rating) values (27, 2);
insert into recipe_rating (recipe_id, rating) values (25, 3);
insert into recipe_rating (recipe_id, rating) values (95, 1);
insert into recipe_rating (recipe_id, rating) values (60, 5);
insert into recipe_rating (recipe_id, rating) values (93, 2);
insert into recipe_rating (recipe_id, rating) values (109, 1);
insert into recipe_rating (recipe_id, rating) values (45, 3);
insert into recipe_rating (recipe_id, rating) values (52, 1);
insert into recipe_rating (recipe_id, rating) values (72, 4);
insert into recipe_rating (recipe_id, rating) values (94, 3);
insert into recipe_rating (recipe_id, rating) values (141, 2);
insert into recipe_rating (recipe_id, rating) values (54, 3);
insert into recipe_rating (recipe_id, rating) values (143, 3);
insert into recipe_rating (recipe_id, rating) values (35, 3);
insert into recipe_rating (recipe_id, rating) values (119, 4);
insert into recipe_rating (recipe_id, rating) values (140, 5);
insert into recipe_rating (recipe_id, rating) values (118, 2);
insert into recipe_rating (recipe_id, rating) values (5, 4);
insert into recipe_rating (recipe_id, rating) values (108, 2);
insert into recipe_rating (recipe_id, rating) values (26, 1);
insert into recipe_rating (recipe_id, rating) values (57, 3);
insert into recipe_rating (recipe_id, rating) values (99, 3);
insert into recipe_rating (recipe_id, rating) values (40, 2);
insert into recipe_rating (recipe_id, rating) values (66, 5);
insert into recipe_rating (recipe_id, rating) values (44, 2);
insert into recipe_rating (recipe_id, rating) values (34, 2);
insert into recipe_rating (recipe_id, rating) values (130, 1);
insert into recipe_rating (recipe_id, rating) values (19, 4);
insert into recipe_rating (recipe_id, rating) values (64, 3);
insert into recipe_rating (recipe_id, rating) values (144, 3);
insert into recipe_rating (recipe_id, rating) values (110, 2);
insert into recipe_rating (recipe_id, rating) values (119, 5);
insert into recipe_rating (recipe_id, rating) values (146, 4);
insert into recipe_rating (recipe_id, rating) values (90, 5);
insert into recipe_rating (recipe_id, rating) values (48, 5);
insert into recipe_rating (recipe_id, rating) values (25, 2);
insert into recipe_rating (recipe_id, rating) values (95, 3);
insert into recipe_rating (recipe_id, rating) values (25, 1);
insert into recipe_rating (recipe_id, rating) values (2, 2);
insert into recipe_rating (recipe_id, rating) values (89, 3);
insert into recipe_rating (recipe_id, rating) values (43, 4);
insert into recipe_rating (recipe_id, rating) values (121, 1);
insert into recipe_rating (recipe_id, rating) values (58, 1);
insert into recipe_rating (recipe_id, rating) values (105, 3);
insert into recipe_rating (recipe_id, rating) values (65, 3);
insert into recipe_rating (recipe_id, rating) values (144, 4);
insert into recipe_rating (recipe_id, rating) values (56, 3);
insert into recipe_rating (recipe_id, rating) values (135, 5);
insert into recipe_rating (recipe_id, rating) values (146, 5);
insert into recipe_rating (recipe_id, rating) values (28, 5);
insert into recipe_rating (recipe_id, rating) values (122, 5);
insert into recipe_rating (recipe_id, rating) values (120, 3);
insert into recipe_rating (recipe_id, rating) values (122, 1);
insert into recipe_rating (recipe_id, rating) values (6, 4);
insert into recipe_rating (recipe_id, rating) values (57, 5);
insert into recipe_rating (recipe_id, rating) values (19, 1);
insert into recipe_rating (recipe_id, rating) values (71, 1);
insert into recipe_rating (recipe_id, rating) values (34, 2);
insert into recipe_rating (recipe_id, rating) values (6, 3);
insert into recipe_rating (recipe_id, rating) values (12, 1);
insert into recipe_rating (recipe_id, rating) values (143, 5);
insert into recipe_rating (recipe_id, rating) values (114, 5);
insert into recipe_rating (recipe_id, rating) values (104, 1);
insert into recipe_rating (recipe_id, rating) values (7, 4);
insert into recipe_rating (recipe_id, rating) values (52, 1);
insert into recipe_rating (recipe_id, rating) values (12, 1);
insert into recipe_rating (recipe_id, rating) values (26, 1);
insert into recipe_rating (recipe_id, rating) values (12, 3);
insert into recipe_rating (recipe_id, rating) values (146, 1);
insert into recipe_rating (recipe_id, rating) values (91, 1);
insert into recipe_rating (recipe_id, rating) values (11, 3);
insert into recipe_rating (recipe_id, rating) values (83, 4);
insert into recipe_rating (recipe_id, rating) values (101, 3);
insert into recipe_rating (recipe_id, rating) values (97, 3);
insert into recipe_rating (recipe_id, rating) values (111, 1);
insert into recipe_rating (recipe_id, rating) values (74, 2);
insert into recipe_rating (recipe_id, rating) values (143, 5);
insert into recipe_rating (recipe_id, rating) values (35, 2);
insert into recipe_rating (recipe_id, rating) values (139, 2);
insert into recipe_rating (recipe_id, rating) values (84, 5);
insert into recipe_rating (recipe_id, rating) values (3, 1);
insert into recipe_rating (recipe_id, rating) values (45, 1);
insert into recipe_rating (recipe_id, rating) values (61, 2);
insert into recipe_rating (recipe_id, rating) values (90, 3);
insert into recipe_rating (recipe_id, rating) values (124, 5);
insert into recipe_rating (recipe_id, rating) values (57, 3);
insert into recipe_rating (recipe_id, rating) values (21, 3);
insert into recipe_rating (recipe_id, rating) values (146, 4);
insert into recipe_rating (recipe_id, rating) values (121, 3);
insert into recipe_rating (recipe_id, rating) values (45, 4);
insert into recipe_rating (recipe_id, rating) values (36, 3);
insert into recipe_rating (recipe_id, rating) values (39, 5);
insert into recipe_rating (recipe_id, rating) values (2, 5);
insert into recipe_rating (recipe_id, rating) values (26, 5);
insert into recipe_rating (recipe_id, rating) values (40, 5);
insert into recipe_rating (recipe_id, rating) values (75, 3);
insert into recipe_rating (recipe_id, rating) values (113, 4);
insert into recipe_rating (recipe_id, rating) values (5, 2);
insert into recipe_rating (recipe_id, rating) values (77, 4);
insert into recipe_rating (recipe_id, rating) values (5, 2);
insert into recipe_rating (recipe_id, rating) values (110, 3);
insert into recipe_rating (recipe_id, rating) values (128, 3);
insert into recipe_rating (recipe_id, rating) values (118, 4);
insert into recipe_rating (recipe_id, rating) values (36, 4);
insert into recipe_rating (recipe_id, rating) values (117, 5);
insert into recipe_rating (recipe_id, rating) values (16, 4);
insert into recipe_rating (recipe_id, rating) values (18, 5);
insert into recipe_rating (recipe_id, rating) values (131, 2);
insert into recipe_rating (recipe_id, rating) values (104, 4);
insert into recipe_rating (recipe_id, rating) values (143, 5);
insert into recipe_rating (recipe_id, rating) values (19, 2);
insert into recipe_rating (recipe_id, rating) values (69, 5);
insert into recipe_rating (recipe_id, rating) values (20, 2);
insert into recipe_rating (recipe_id, rating) values (52, 2);
insert into recipe_rating (recipe_id, rating) values (146, 4);
insert into recipe_rating (recipe_id, rating) values (103, 4);
insert into recipe_rating (recipe_id, rating) values (64, 2);
insert into recipe_rating (recipe_id, rating) values (129, 5);
insert into recipe_rating (recipe_id, rating) values (30, 5);
insert into recipe_rating (recipe_id, rating) values (127, 5);
insert into recipe_rating (recipe_id, rating) values (113, 5);
insert into recipe_rating (recipe_id, rating) values (64, 1);
insert into recipe_rating (recipe_id, rating) values (87, 1);
insert into recipe_rating (recipe_id, rating) values (89, 5);
insert into recipe_rating (recipe_id, rating) values (80, 5);
insert into recipe_rating (recipe_id, rating) values (51, 5);
insert into recipe_rating (recipe_id, rating) values (120, 4);
insert into recipe_rating (recipe_id, rating) values (85, 4);
insert into recipe_rating (recipe_id, rating) values (25, 3);
insert into recipe_rating (recipe_id, rating) values (65, 5);
insert into recipe_rating (recipe_id, rating) values (42, 3);
insert into recipe_rating (recipe_id, rating) values (123, 4);
insert into recipe_rating (recipe_id, rating) values (108, 2);
insert into recipe_rating (recipe_id, rating) values (71, 3);
insert into recipe_rating (recipe_id, rating) values (128, 4);
insert into recipe_rating (recipe_id, rating) values (110, 4);
insert into recipe_rating (recipe_id, rating) values (145, 4);
insert into recipe_rating (recipe_id, rating) values (58, 1);
insert into recipe_rating (recipe_id, rating) values (5, 5);
insert into recipe_rating (recipe_id, rating) values (15, 5);
insert into recipe_rating (recipe_id, rating) values (15, 5);
insert into recipe_rating (recipe_id, rating) values (74, 4);
insert into recipe_rating (recipe_id, rating) values (65, 3);
insert into recipe_rating (recipe_id, rating) values (42, 4);
insert into recipe_rating (recipe_id, rating) values (146, 4);
insert into recipe_rating (recipe_id, rating) values (139, 5);
insert into recipe_rating (recipe_id, rating) values (135, 4);
insert into recipe_rating (recipe_id, rating) values (93, 3);
insert into recipe_rating (recipe_id, rating) values (112, 5);
insert into recipe_rating (recipe_id, rating) values (68, 5);
insert into recipe_rating (recipe_id, rating) values (74, 3);
insert into recipe_rating (recipe_id, rating) values (3, 2);
insert into recipe_rating (recipe_id, rating) values (54, 4);
insert into recipe_rating (recipe_id, rating) values (32, 5);
insert into recipe_rating (recipe_id, rating) values (143, 2);
insert into recipe_rating (recipe_id, rating) values (99, 5);
insert into recipe_rating (recipe_id, rating) values (65, 4);
insert into recipe_rating (recipe_id, rating) values (92, 4);
insert into recipe_rating (recipe_id, rating) values (104, 1);
insert into recipe_rating (recipe_id, rating) values (99, 5);
insert into recipe_rating (recipe_id, rating) values (57, 5);
insert into recipe_rating (recipe_id, rating) values (79, 3);
insert into recipe_rating (recipe_id, rating) values (94, 1);
insert into recipe_rating (recipe_id, rating) values (103, 2);
insert into recipe_rating (recipe_id, rating) values (114, 4);
insert into recipe_rating (recipe_id, rating) values (39, 2);
insert into recipe_rating (recipe_id, rating) values (9, 1);
insert into recipe_rating (recipe_id, rating) values (96, 1);
insert into recipe_rating (recipe_id, rating) values (49, 4);
insert into recipe_rating (recipe_id, rating) values (72, 1);
insert into recipe_rating (recipe_id, rating) values (97, 2);
insert into recipe_rating (recipe_id, rating) values (142, 4);
insert into recipe_rating (recipe_id, rating) values (136, 3);
insert into recipe_rating (recipe_id, rating) values (127, 3);
insert into recipe_rating (recipe_id, rating) values (144, 2);
insert into recipe_rating (recipe_id, rating) values (60, 4);
insert into recipe_rating (recipe_id, rating) values (142, 4);
insert into recipe_rating (recipe_id, rating) values (133, 4);
insert into recipe_rating (recipe_id, rating) values (7, 3);
insert into recipe_rating (recipe_id, rating) values (62, 1);
insert into recipe_rating (recipe_id, rating) values (135, 2);
insert into recipe_rating (recipe_id, rating) values (134, 1);
insert into recipe_rating (recipe_id, rating) values (1, 1);
insert into recipe_rating (recipe_id, rating) values (147, 2);
insert into recipe_rating (recipe_id, rating) values (43, 4);
insert into recipe_rating (recipe_id, rating) values (138, 4);
insert into recipe_rating (recipe_id, rating) values (9, 3);
insert into recipe_rating (recipe_id, rating) values (144, 5);
insert into recipe_rating (recipe_id, rating) values (96, 2);
insert into recipe_rating (recipe_id, rating) values (117, 2);
insert into recipe_rating (recipe_id, rating) values (65, 5);
insert into recipe_rating (recipe_id, rating) values (117, 5);
insert into recipe_rating (recipe_id, rating) values (26, 1);
insert into recipe_rating (recipe_id, rating) values (63, 2);
insert into recipe_rating (recipe_id, rating) values (40, 2);
insert into recipe_rating (recipe_id, rating) values (69, 3);
insert into recipe_rating (recipe_id, rating) values (139, 3);
insert into recipe_rating (recipe_id, rating) values (62, 4);
insert into recipe_rating (recipe_id, rating) values (45, 3);
insert into recipe_rating (recipe_id, rating) values (66, 3);
insert into recipe_rating (recipe_id, rating) values (51, 1);
insert into recipe_rating (recipe_id, rating) values (54, 4);
insert into recipe_rating (recipe_id, rating) values (139, 3);
insert into recipe_rating (recipe_id, rating) values (147, 4);
insert into recipe_rating (recipe_id, rating) values (120, 2);
insert into recipe_rating (recipe_id, rating) values (61, 2);
insert into recipe_rating (recipe_id, rating) values (95, 4);
insert into recipe_rating (recipe_id, rating) values (117, 2);
insert into recipe_rating (recipe_id, rating) values (123, 3);
insert into recipe_rating (recipe_id, rating) values (47, 1);
insert into recipe_rating (recipe_id, rating) values (117, 2);
insert into recipe_rating (recipe_id, rating) values (116, 1);
insert into recipe_rating (recipe_id, rating) values (99, 4);
insert into recipe_rating (recipe_id, rating) values (83, 4);
insert into recipe_rating (recipe_id, rating) values (79, 5);
insert into recipe_rating (recipe_id, rating) values (60, 3);
insert into recipe_rating (recipe_id, rating) values (87, 4);
insert into recipe_rating (recipe_id, rating) values (62, 4);
insert into recipe_rating (recipe_id, rating) values (109, 3);
insert into recipe_rating (recipe_id, rating) values (51, 5);
insert into recipe_rating (recipe_id, rating) values (123, 1);
insert into recipe_rating (recipe_id, rating) values (64, 4);
insert into recipe_rating (recipe_id, rating) values (89, 2);
insert into recipe_rating (recipe_id, rating) values (14, 1);
insert into recipe_rating (recipe_id, rating) values (144, 3);
insert into recipe_rating (recipe_id, rating) values (51, 5);
insert into recipe_rating (recipe_id, rating) values (32, 1);
insert into recipe_rating (recipe_id, rating) values (144, 2);
insert into recipe_rating (recipe_id, rating) values (106, 4);
insert into recipe_rating (recipe_id, rating) values (79, 1);
insert into recipe_rating (recipe_id, rating) values (132, 5);
insert into recipe_rating (recipe_id, rating) values (86, 1);
insert into recipe_rating (recipe_id, rating) values (30, 5);
insert into recipe_rating (recipe_id, rating) values (10, 5);
insert into recipe_rating (recipe_id, rating) values (45, 2);
insert into recipe_rating (recipe_id, rating) values (66, 1);
insert into recipe_rating (recipe_id, rating) values (118, 1);
insert into recipe_rating (recipe_id, rating) values (15, 2);
insert into recipe_rating (recipe_id, rating) values (142, 2);
insert into recipe_rating (recipe_id, rating) values (115, 4);
insert into recipe_rating (recipe_id, rating) values (90, 4);
insert into recipe_rating (recipe_id, rating) values (1, 2);
insert into recipe_rating (recipe_id, rating) values (44, 1);
insert into recipe_rating (recipe_id, rating) values (7, 4);
insert into recipe_rating (recipe_id, rating) values (22, 5);
insert into recipe_rating (recipe_id, rating) values (36, 3);
insert into recipe_rating (recipe_id, rating) values (138, 2);
insert into recipe_rating (recipe_id, rating) values (126, 3);
insert into recipe_rating (recipe_id, rating) values (145, 3);
insert into recipe_rating (recipe_id, rating) values (149, 1);
insert into recipe_rating (recipe_id, rating) values (138, 1);
insert into recipe_rating (recipe_id, rating) values (74, 3);
insert into recipe_rating (recipe_id, rating) values (140, 3);
insert into recipe_rating (recipe_id, rating) values (149, 1);
insert into recipe_rating (recipe_id, rating) values (49, 1);
insert into recipe_rating (recipe_id, rating) values (142, 1);
insert into recipe_rating (recipe_id, rating) values (140, 1);
insert into recipe_rating (recipe_id, rating) values (70, 1);
insert into recipe_rating (recipe_id, rating) values (16, 5);
insert into recipe_rating (recipe_id, rating) values (51, 1);
insert into recipe_rating (recipe_id, rating) values (127, 5);
insert into recipe_rating (recipe_id, rating) values (14, 3);
insert into recipe_rating (recipe_id, rating) values (75, 1);
insert into recipe_rating (recipe_id, rating) values (76, 4);
insert into recipe_rating (recipe_id, rating) values (35, 3);
insert into recipe_rating (recipe_id, rating) values (144, 2);
insert into recipe_rating (recipe_id, rating) values (102, 3);
insert into recipe_rating (recipe_id, rating) values (19, 5);
insert into recipe_rating (recipe_id, rating) values (135, 5);
insert into recipe_rating (recipe_id, rating) values (103, 2);
insert into recipe_rating (recipe_id, rating) values (82, 1);
insert into recipe_rating (recipe_id, rating) values (5, 3);
insert into recipe_rating (recipe_id, rating) values (125, 4);
insert into recipe_rating (recipe_id, rating) values (91, 3);
insert into recipe_rating (recipe_id, rating) values (69, 1);
insert into recipe_rating (recipe_id, rating) values (7, 1);
insert into recipe_rating (recipe_id, rating) values (72, 4);
insert into recipe_rating (recipe_id, rating) values (83, 4);
insert into recipe_rating (recipe_id, rating) values (44, 4);
insert into recipe_rating (recipe_id, rating) values (56, 2);
insert into recipe_rating (recipe_id, rating) values (127, 1);
insert into recipe_rating (recipe_id, rating) values (15, 4);
insert into recipe_rating (recipe_id, rating) values (125, 1);
insert into recipe_rating (recipe_id, rating) values (86, 1);
insert into recipe_rating (recipe_id, rating) values (8, 5);
insert into recipe_rating (recipe_id, rating) values (123, 1);
insert into recipe_rating (recipe_id, rating) values (125, 4);
insert into recipe_rating (recipe_id, rating) values (97, 1);
insert into recipe_rating (recipe_id, rating) values (148, 2);
insert into recipe_rating (recipe_id, rating) values (59, 4);
insert into recipe_rating (recipe_id, rating) values (49, 5);
insert into recipe_rating (recipe_id, rating) values (140, 5);
insert into recipe_rating (recipe_id, rating) values (137, 5);
insert into recipe_rating (recipe_id, rating) values (86, 5);
insert into recipe_rating (recipe_id, rating) values (117, 4);
insert into recipe_rating (recipe_id, rating) values (141, 2);
insert into recipe_rating (recipe_id, rating) values (74, 5);
insert into recipe_rating (recipe_id, rating) values (94, 2);
insert into recipe_rating (recipe_id, rating) values (128, 4);
insert into recipe_rating (recipe_id, rating) values (86, 3);
insert into recipe_rating (recipe_id, rating) values (88, 2);
insert into recipe_rating (recipe_id, rating) values (106, 4);
insert into recipe_rating (recipe_id, rating) values (35, 2);
insert into recipe_rating (recipe_id, rating) values (147, 2);
insert into recipe_rating (recipe_id, rating) values (118, 2);
insert into recipe_rating (recipe_id, rating) values (16, 2);
insert into recipe_rating (recipe_id, rating) values (102, 5);
insert into recipe_rating (recipe_id, rating) values (3, 3);
insert into recipe_rating (recipe_id, rating) values (148, 5);
insert into recipe_rating (recipe_id, rating) values (35, 5);
insert into recipe_rating (recipe_id, rating) values (123, 5);
insert into recipe_rating (recipe_id, rating) values (10, 2);
insert into recipe_rating (recipe_id, rating) values (138, 5);
insert into recipe_rating (recipe_id, rating) values (84, 2);
insert into recipe_rating (recipe_id, rating) values (28, 5);
insert into recipe_rating (recipe_id, rating) values (123, 2);
insert into recipe_rating (recipe_id, rating) values (77, 2);
insert into recipe_rating (recipe_id, rating) values (63, 3);
insert into recipe_rating (recipe_id, rating) values (48, 5);
insert into recipe_rating (recipe_id, rating) values (47, 1);
insert into recipe_rating (recipe_id, rating) values (134, 4);
insert into recipe_rating (recipe_id, rating) values (27, 2);
insert into recipe_rating (recipe_id, rating) values (70, 4);
insert into recipe_rating (recipe_id, rating) values (36, 2);
insert into recipe_rating (recipe_id, rating) values (34, 2);
insert into recipe_rating (recipe_id, rating) values (148, 4);
insert into recipe_rating (recipe_id, rating) values (61, 3);
insert into recipe_rating (recipe_id, rating) values (38, 5);
insert into recipe_rating (recipe_id, rating) values (87, 1);
insert into recipe_rating (recipe_id, rating) values (41, 3);
insert into recipe_rating (recipe_id, rating) values (70, 1);
insert into recipe_rating (recipe_id, rating) values (117, 5);
insert into recipe_rating (recipe_id, rating) values (53, 5);
insert into recipe_rating (recipe_id, rating) values (147, 2);
insert into recipe_rating (recipe_id, rating) values (106, 2);
insert into recipe_rating (recipe_id, rating) values (99, 3);
insert into recipe_rating (recipe_id, rating) values (25, 5);
insert into recipe_rating (recipe_id, rating) values (123, 1);
insert into recipe_rating (recipe_id, rating) values (72, 3);
insert into recipe_rating (recipe_id, rating) values (4, 3);
insert into recipe_rating (recipe_id, rating) values (58, 4);
insert into recipe_rating (recipe_id, rating) values (41, 2);
insert into recipe_rating (recipe_id, rating) values (35, 2);
insert into recipe_rating (recipe_id, rating) values (98, 3);
insert into recipe_rating (recipe_id, rating) values (132, 2);
insert into recipe_rating (recipe_id, rating) values (70, 3);
insert into recipe_rating (recipe_id, rating) values (89, 3);
insert into recipe_rating (recipe_id, rating) values (3, 4);
insert into recipe_rating (recipe_id, rating) values (16, 1);
insert into recipe_rating (recipe_id, rating) values (65, 4);
insert into recipe_rating (recipe_id, rating) values (41, 1);
insert into recipe_rating (recipe_id, rating) values (48, 1);
insert into recipe_rating (recipe_id, rating) values (69, 3);
insert into recipe_rating (recipe_id, rating) values (49, 1);
insert into recipe_rating (recipe_id, rating) values (80, 3);
insert into recipe_rating (recipe_id, rating) values (70, 3);
insert into recipe_rating (recipe_id, rating) values (50, 4);
insert into recipe_rating (recipe_id, rating) values (10, 5);
insert into recipe_rating (recipe_id, rating) values (33, 4);
insert into recipe_rating (recipe_id, rating) values (50, 5);
insert into recipe_rating (recipe_id, rating) values (126, 3);
insert into recipe_rating (recipe_id, rating) values (109, 3);
insert into recipe_rating (recipe_id, rating) values (120, 4);
insert into recipe_rating (recipe_id, rating) values (29, 2);
insert into recipe_rating (recipe_id, rating) values (99, 4);
insert into recipe_rating (recipe_id, rating) values (42, 2);
insert into recipe_rating (recipe_id, rating) values (90, 1);
